///<reference path='Scripts/typings/node/node.d.ts'/>
///<reference path='@op.ts'/>
///<reference path='InterfaceGenerator.ts'/>
///<reference path='@op.JsonReflector.ts'/>


module Examples{
	
	declare var WorkerGlobalScope: any;
	
	export interface IAddress{
		Street?: string;
		ZipCode?: string;
	}
	
	export class Address implements IAddress{
		
		@op.toProp()
		public Street : string;
		
		@op.toProp()
		public ZipCode : string;
		
	}
	
	
	
	export interface IEmployee{
		Surname?: string;
		FirstName?: string;
		MiddleName?: string;
		HomeAddress?:  IAddress;
		
		
	} /*AutoGenerated:*/ class EmployeeImpl{}
	
	export class EmployeeFactory{
		public static get instance(){
			return new Employee();
		}
	}
	
	@InterfaceGenerator.autoGen("Information about an employee")
	export class Employee implements IEmployee{
		
		// public static New(employee: IEmployee){
		// 	// const employeeImpl = new Employee();
		// 	// Object['assign'](employeeImpl, employee);
		// 	// return employeeImpl;
		// 	return op.createNew<IEmployee, Employee>(employee, Employee);
		// }
		
		
		
		
		@op.plopIntoMeta<IColumnDefCategory>({
			ColumnDef: {
				hide: true,
			}
		})
		public static defaultAddress : Address;
		
		@op.initProp()
		public get Surname() : string{return null;} 
		public set Surname(v: string){}
		
		private _firstName : string;
		
		@op.initProp()
		public get FirstName() : string{
			return this._firstName;
		}
		public set FirstName(val: string){
			this._firstName = val;
		}
		
		@op.plopIntoMeta<IColumnDefCategory>({
			ColumnDef: {
				hide: true,
			}
		})
		@op.description(`Middle Name of Employee`)
		public MiddleName : string;
		
		@op.toProp()
		public HomeAddress : Address;
		
		@op.plopIntoMeta<IColumnDefCategory>({
			ColumnDef: {
				hide: true,
			}
		})
		public DriveHome() : void {
			
		}
		
		@op.reflectionType(Address)
		public TempAddress : IAddress;
		
		
		public findLocation(@op._ emp: Employee, s: string) : boolean{
			return true;
		}
		
	}
	
	// Object.defineProperty(Employee, 'instance', {
    //   get: () =>{
	// 	  return new Employee();
	//   },
    //   enumerable: true,
    //   configurable: true
    // });
	
	console.log('reflect Employee => ');
	console.log(op.reflect(Employee, true));
	
	const ColumnDef = 'ColumnDef';
	interface IColumnDef{
		width?: number;
		hide?: boolean;
		title?: string;
	}
	
	interface IColumnDefCategory{
		ColumnDef: IColumnDef; //TODO:  Replace "ColumnDef" with Symbol?
	}
	
	const Constraints = 'Constraints';
	interface IConstraints{
		maxLength?: number;
	}
	
	interface IConstraintCategory{
		Constraints : IConstraints; //TODO:  Replace "Contraints" with Symbol?
	}
	
	
	const setTitleToFieldNameUC: (fieldName: string) => IColumnDefCategory = function(fieldName: string){
		return {
			ColumnDef: {
				title: fieldName.toUpperCase(),
			}
		}
	}
	
	export class AddressView extends Address implements IAddress{
		//@op.toProp()
		@op.plopIntoMeta<IConstraintCategory>({
			Constraints:{
				maxLength: 200
			}
		})
		public street: string;
	}
	
	export class EmployeeView extends Employee implements IEmployee{
		@op.plopIntoMeta<IConstraintCategory>({
			Constraints:{
				maxLength: 10
			}
		})
		@op.plopIntoMeta<IColumnDefCategory>({
			ColumnDef: {
				width: 200,
			}
		})
		@op.metaPlopper<IColumnDefCategory>(setTitleToFieldNameUC)
		MiddleName: string;
		
		@op.plopIntoMeta<IColumnDefCategory>({
			ColumnDef: {
				width: 100,
			}
		})
		Surname: string;
		
		@op.toProp()
		HomeAddress: AddressView;
		
	}
	
	// hook global op
    (function(__global: any) {
        if (typeof __global.Examples !== "undefined") {
            if (__global.Examples !== Examples) {
                for (var p in Examples) {
                    __global.Examples[p] = (<any>Examples)[p];
                }
            }
        }
        else {
            __global.Examples = Examples;
        }
    })(
        typeof window !== "undefined" ? window :
            typeof WorkerGlobalScope !== "undefined" ? self :
                typeof global !== "undefined" ? global :
                    Function("return this;")());
	
}

